refactor: Koota glowup
birbhouse-games/dying-sun pull request #7
Opened 2024-12-24 05:41 UTC by krispya

WIP

2024-12-27 02:59 UTC, krispya commented
The initial conversion is done. I will be making some bug and QoL improvements to Koota before marking it ready to merge.

2025-01-03 21:57 UTC, krispya commented
Koota update is done and this PR has been updated with the latest QoL. I can continue with refactoring in separate PRs, but I figure this is better off reviewed with code close to the original.

2025-01-06 06:26 UTC, trezy commented on packages/game/src/store/traits/Attacker.ts
> +/* eslint-disable jsdoc/require-jsdoc */
👀

2025-01-06 06:26 UTC, trezy commented on packages/game/src/store/traits/Actor.ts
> +/* eslint-disable jsdoc/require-jsdoc */
👀

2025-01-06 16:46 UTC, trezy requested changes

2025-01-06 16:46 UTC, trezy commented on packages/game/src/store/traits/Attacker.ts
> +/* eslint-disable jsdoc/require-jsdoc */
👀

2025-01-06 16:46 UTC, trezy commented on packages/game/src/typedefs/AttackState.ts
> +// I'll look to fix this in Koota and switch back to interface.
You left this comment, but based on the diff nothing actually changed here? 🤔

2025-01-06 16:46 UTC, trezy commented on packages/game/src/store/traits/Actor.ts
> +/* eslint-disable jsdoc/require-jsdoc */
👀

2025-01-06 16:46 UTC, trezy commented on packages/game/src/components/DebugRenderer/DebugRenderer.tsx
> +	// This is very hacky and should be refactored
Add `TODO: ` to the beginning of this comment so it shows up in searches.

2025-01-06 16:46 UTC, trezy commented on src/components/ActorView/ActorView.tsx
> +>>>>>>>> main:packages/game/src/components/Actor/Actor.tsx
Looks like you missed a merge diff.

2025-01-06 16:46 UTC, trezy commented on src/components/ActorView/ActorView.tsx
> +>>>>>>>> main:packages/game/src/components/Actor/Actor.tsx
Another merge diff.

2025-01-07 05:38 UTC, trezy approved these changes

2025-01-07 05:41 UTC, merged